version: '3.2'

services:
  torproxy_webserver:
    image: httpd
    container_name: 'torproxy_webserver'
    networks:
      - network

  torproxy:
    image: torproxy:1.0.2
    container_name: 'torproxy'
    depends_on:
      - torproxy_webserver
    volumes:
      - ./Volumes/Keys:/var/lib/tor/hiddenservicename
      - ./Volumes/Logs:/var/log/tor
    environment:
      - hiddenservicedir=hiddenservicename
      - hiddenserviceport=80
      - hiddenserviceaddress=torproxy_webserver:80
      - lognotice=true
      - logdebug=false
    networks:
      - network

networks:
  network:
    name: network
