name: buildpipeline
on:
  workflow_dispatch:
    inputs:
      TargetEnvironmentType:
        description: "Target environment-type for the build (e.g. QualityCheck, Productive)."
        required: false
        default: QualityCheck
      FastLane:
        description: "Fast lane for build-pipeline"
        required: false
        default: false
env:
  IS_RUNNING_IN_SERVER_PIPELINE: "true"
  IS_RUNNING_IN_GITHUB_PIPELINE: "true"
jobs:
  build-pipeline:
    runs-on: [self-hosted, scriptcollection]
    container:
      image: aniondev/scbuilder:v1.2.13
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update scriptcollection
        run: pip3 install scriptcollection --upgrade
      - name: Prepare build-pipeline
        run: scpreparebuildpipelineforgithub
      - name: Build codeunits
        run: scbuildcodeunits --assertnonewchanges --verbosity 4 --targetenvironment "${{ inputs.TargetEnvironmentType }}"${{ inputs.FastLane == 'true' && ' --fastlane' || '' }}
      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: Other/Resources/Artifacts
          if-no-files-found: error
